version: '3'
services:
  nikto:
    build:
      context: .
    container_name: nikto_local
    command: [$NIKTO_DOMAIN]
    volumes:
      - ./nikto-reports:/reports
    stdin_open: true
    tty: true